### ISSUE TITLE
Bug in Loading Shared States

### ISSUE THREAD

**Issue by arrabito** [DIRACGrid/WebAppDIRAC#159]
We've discovered some mis-behaviour when Loading Shared States. What happens is that the Applications of the Shared State are correctly loaded, but they are not in the correct location within the desktop, neither they have the correct size.

**Comment by zmathe** [comment]
@arrabito Could you please check it? Maybe, better to use the Tab view in order to avoid this issue.

**Comment by zmathe** [comment]
@arrabito Could you please check? otherwise I will close.

**Comment by arrabito** [comment]
I don't have anymore saved states to check this feature. So I tried to save a new  one, but I get this error:
Operation failed: MySQL Error ( 1131 : Execution failed.: ( 1054: Unknown column 'PublishAccess' in 'field list' )).
Maybe I've missed some updates?
Anyway, I think you can close it and I will check again as soon as I will have fixed this other issue.
