### ISSUE TITLE
Missing option in the  Accounting, Data Operation Category

### ISSUE THREAD

**Issue by arrabito** [DIRACGrid/WebAppDIRAC#160]
In the Accounting, Data Operation Category, there is a missing option in the Group By selector with respect to the old portal, that I found useful. This is the:
Group By = Channel 
option 
I don't know if this was done on porpouse.
Thanks in advance,
Luisa

**Comment by zmathe** [comment]
fixed: https://github.com/DIRACGrid/WebAppDIRAC/blob/integration/WebApp/static/DIRAC/AccountingPlot/classes/AccountingPlot.js#L689
