### ISSUE TITLE
[ERROR] Could not compile binaries version v6r12p35

### ISSUE THREAD

**Issue by aamster** [DIRACGrid/WebAppDIRAC#188]
Mac OS version 10.10. 

I am following the guide at http://diracgrid.org/files/docs/DeveloperGuide/WebAppDIRAC/InstallWebAppDIRAC/index.html to install DIRAC and WebAppDIRAC, which says that it is for Mac OS users. I am stuck at step 3. I clone the repo, and then attempt to run ./DIRAC/Core/scripts/dirac-install.py -r v6r12p35 -X -t server but get [ERROR] Could not compile binaries because of [ERROR] http://lhcbproject.web.cern.ch/lhcbproject/dist/Dirac_project/installSource/Externals-server-v6r2-Darwin_x86_64_10.10-python27.tar.gz does not exist. It seems like DIRAC server for any version for Mac OS does not exist.

What do you suggest?

**Comment by atsareg** [comment]
We indeed do not provide the server distribution for Mac OS. Is it crucial for you ? Are you really going to run DIRAC services on your Mac or it is for development purposes ?

**Comment by aamster** [comment]
It is for development purposes. I'm assuming I can skip this step and then define a valid server URL in the dirac.cfg file and then proceed from there?

**Comment by atsareg** [comment]
For development you do not really need a server type distribution on your Mac. For example, you will install MySQL in the Mac way rather than in the DIRAC way. In your tests you can define your server URL as localhost in the local configuration, no need necessarily for the Configuration Service

**Comment by zmathe** [comment]
Yes, You do not need. You can use the client. 
Could you please try: ./DIRAC/Core/scripts/dirac-install.py -r v6r12p35 -X -t client ?
We do not have the external for the server.

**Comment by aamster** [comment]
Thanks, the client installed successfully.

**Comment by atsareg** [comment]
For the record - this kind of questions are better put in the DIRAC user forum rather than here. This concerns the other issue that you have started. I close the issues here. Please, register ( if not yet done ) to the DIRAC user and/or developer forums
