### ISSUE TITLE
Pip install GSI fails

### ISSUE THREAD

**Issue by aamster** [DIRACGrid/WebAppDIRAC#189]
Mac OS 10.10

I am trying to install the dependency GSI using pip. 

It fails with 
clang: error: no such file or directory: '/private/tmp/pip_build_root/GSI/src/util.c'

clang: error: no input files

error: command 'cc' failed with exit status 1

What do you suggest?

**Comment by zmathe** [comment]
Have you tried?
./DIRAC/Core/scripts/dirac-install.py -r v6r12p35 -X -t client

**Comment by aamster** [comment]
Yes, the client was installed successfully.

**Comment by zmathe** [comment]
you do not need to install GSI. You can continue with the next step (4).

**Comment by atsareg** [comment]
Please, consider using the DIRAC forum for this kind of questions

**Comment by tianzhiyu** [comment]
Pip install GSI on Windows7. 
It fails with    cl: Command line error D8021: invalid numeric argumentCommand line error D8021: invalid numeric argument '/Wno-deprecated-declarations'

**Comment by tianzhiyu** [comment]
Pip install GSI on Windows7. 
It fails with 
cl: Command line error D8021: invalid numeric argument '/Wno-deprecated-declarations'
