### ISSUE TITLE
WebApp cannot control RSS with v6

### ISSUE THREAD

**Issue by Kiyoshi-Hayasaka** [DIRACGrid/WebAppDIRAC#225]
Hi,
current WebApp for RSS
/opt/dirac/pro/WebAppDIRAC/WebApp/handler/ResourceSummaryHandler.py
uses setStatus of ResourceStatus/Publisher via RPC like
    res = yield self.threadTask( pub.setStatus, 'Resource',
                         str( requestParams[ 'name' ][ 0 ] ),
                         str( requestParams[ 'statusType' ][ 0 ] ),
                         str( requestParams[ 'status' ][ 0 ] ),
                         str( requestParams[ 'elementType' ][ 0 ] ),
                         username,
                         str( requestParams[ 'lastCheckTime' ][ 0 ] ) )
But, according to
https://github.com/DIRACGrid/DIRAC/commit/b75b82c66f3bd0162b692b5b81dda74e578f21cd
After v7, setStatus is newly added. So, with v6, we cannot operate RSS via WebApp...
Can you make some workaround without using setStatus for v6?
Or should I ask VanillaDIRAC to add setStatus into v6, too?
Thank you in advance,
K.Hayasaka

**Comment by zmathe** [comment]
I do not see any problem. We have setStatus in DIRAC v6r14 and we will have setStatus in v6r17 as well. I do not see your problem.

**Comment by hmiyake** [comment]
Hi all,

If I'm correct, setStatus has been backported since v6r15-pre9
https://github.com/DIRACGrid/DIRAC/commit/7a9f8a616565db3a984c0cbbd319e63ebae74569
v6r14 support might be provided by VO extension.
Could you check it?

Cheers,
Hideki
