### ISSUE TITLE
Custom background image, favicon and waiting animation

### ISSUE THREAD

**Issue by petricm** [DIRACGrid/WebAppDIRAC#228]
Please add a possibility to specify backgound image, favicon and waiting animation (_logo_waiting.gif) in either CS or web.cfg.

**Comment by zmathe** [comment]
Is this fixed? I think yes. I cannot remember:)

**Comment by petricm** [comment]
You never told me that you fixed it. But if you fixed it how do you configure? I still patch it like

cp dirac_* /opt/dirac/pro/WebAppDIRAC/WebApp/static/core/img/wallpapers/.
cp _logo_waiting.gif* /opt/dirac/pro/WebAppDIRAC/WebApp/static/core/img/icons/system/.
cp favicon.ico* /opt/dirac/pro/WebAppDIRAC/WebApp/static/core/img/icons/system/.

**Comment by fstagni** [comment]
So?

**Comment by zmathe** [comment]
Not all information was configurable. I just added the missing parts:
https://github.com/DIRACGrid/WebAppDIRAC/pull/285
In the next patch v6r19p? will be available and it can be configured using the web.cfg file for example:
```
WebApp
{
   Logo =xxx
   BackgroundImage =xxxx
   Icon = xxxxx
....
}
```

**Comment by fstagni** [comment]
...I guess this can be closed!
