### ISSUE TITLE
Detection wrong extension while compilation of static files

### ISSUE THREAD

**Issue by myco** [DIRACGrid/WebAppDIRAC#231]
When I run dirac-webapp-compile the command doesn't detect properly directory with extension. Instead it detect .svn directory only in WebApp/static/.
It is my development instalation so I want to have .svn directory there.
When I remove .svn directory than dirac-webapp-compile command works fine and detect my static files to compile.

**Comment by zmathe** [comment]
Why you want to compile the code when you develop? Every time when you modify, you have to compile...
Not: The compiled code should be used in production.

**Comment by myco** [comment]
I don't want to compile but WebAppDIRAC framework require 'build' directories. I tried to switch DevelopMode = True/False but it anyway wants build directories.

Anyway, back to main request, extension detection for compiling can not detect appropriate directory if there is for example .svn/

**Comment by zmathe** [comment]
How do you want to change to DevelopMode=True?
As I said before when you compile the web, you do not have appropriate directory like .svn or .babla, etc.

**Comment by zmathe** [comment]
this is fixed in #281
