### ISSUE TITLE
Minor inconveniences

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/WebAppDIRAC#234]
Pilot Monitor
- [x] When entering something in the "pilot job reference", the other fields are greyed out, but are still used for the selection, often times resulting in errors.

Pilot Summary:
- [x] There is no column for "Failed" pilots, Failed pilots are not counted in the Aborted column either.

Job Monitor:
- [x] Pilot --> LoggingInfo doesn't seem to work, though it is available when going through the pilot monitor

Transformation Monitor
- [x] FileRetries: Here one cannot get the list of files, which is possible in the FileStatus window
- [x] The AdditionalParams can be much longer than one line and the "show value" option from the old webportal no longer exists. Would be nice if these parameters could be shown with line wrapping
- [x] When sorting the transformations according to "Processed (%)" and then clicking submit again an error shows up "Operation failed: {"success": "false", "error": "Execution failed.: ( 1054: Unknown column 'Files_PercentProcessed' in 'order clause' )"}." The same is true for some other fields, e.g. TotalCreated. But I  didn't try all of them

Request Monitor:
- [x] Pagination: There is no pagination in the Request Monitor. Only N requests are shown, but the buttons to move to the next N requests do not work.

**Comment by zmathe** [comment]
I can not fix the non ticked checkboxes...

**Comment by andresailer** [comment]
Thanks for fixing these issues! Can you elaborate a little bit why the unticked items cannot be solved?

**Comment by zmathe** [comment]
ops, sorry I have not ticked correctly. There is only one unticked item, which can not be solved because the DIRAC service does not provide the data. If I remember correctly the status Failed is not in the DB. This is DIRAC service limitation. I can add the Failed field to the page, but it will be not filled...

**Comment by andresailer** [comment]
Strange, because in the Pilot Monitor I can select Status "Failed", and get Failed Pilots. So it must come from somewhere.

**Comment by zmathe** [comment]
I had a look agin. This is the method, which does not return the failed status: https://github.com/DIRACGrid/DIRAC/blob/integration/WorkloadManagementSystem/DB/PilotAgentsDB.py#L625
