### ISSUE TITLE
SystemAdministrator should directly query ComponentMonitoring

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/WebAppDIRAC#252]
At the moment the SystemAdministrator is querying each server which then might turn to the ComponentMonitoring itself.
https://github.com/DIRACGrid/WebAppDIRAC/blob/integration/WebApp/handler/SystemAdministrationHandler.py#L56

Wouldn't it make sense to first query the ComponentMonitoring directly?

**Comment by zmathe** [comment]
This was the original goal, but it is not implemented that way. It needs further improvement. But this is still faster than browsing the machine file system.

**Comment by zmathe** [comment]
The host are retrieved for the ComponentMonitoring, the host info are retrieved directly from the host. So, the SystemAdministrator page contains information, which are not in the component database for example host info. I would say when the elastic search based component monitoring contains this information, then the SystemAdministrator can be changed...

**Comment by fstagni** [comment]
Looks like fixed.
