### ISSUE TITLE
Colors in Job Monitor pie charts

### ISSUE THREAD

**Issue by zmathe** [DIRACGrid/WebAppDIRAC#269]
Hi Zoltan,
Would it be possible to use the same colors in the pie charts of JobMonitor as are used in the square boxes for the statistics… I would it quite disturbing using grouping by Status to see “Running” being red and “Failed” being blue ;-)) while in the list on the left it is the opposite ;-)
Thanks!
Cheers,
Philippe

**Comment by petricm** [comment]
What is the status of this?

**Comment by zmathe** [comment]
no news. First we have to use extjs 6

**Comment by zmathe** [comment]
I have changed the colour. I am using the colour Palette of the old portal.
![screen shot 2018-01-25 at 18 29 46](https://user-images.githubusercontent.com/981448/35402785-e2cae1c8-01fd-11e8-9c98-ee3fac4f4dac.png)
