### ISSUE TITLE
See the configuration changes before commiting

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/WebAppDIRAC#272]
Could we, instead of having just a message saying "are you sure you want to commit", actually see the diff before committing ?
There is a button to see the diff, but first of all, it is buggy (if you click that, the commit button disappear), and it is not really good, because you have to do it by yourself, and also it shows you the whoooooooooooole CS, instead of just what has been modified.

Thanks !

**Comment by zmathe** [comment]
See the attached screen shoot:
![screen shot 2018-01-25 at 16 57 45](https://user-images.githubusercontent.com/981448/35397898-f34a2570-01f0-11e8-85fc-0657d3ce1389.png)

**Comment by chaen** [comment]
Thanks ! This however has a few bugs, not everything is shown in the diff. I'll open bug report next time I see it :) But thanks for the feature !
