### ISSUE TITLE
Getting output sandbox when it is an LFN

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/WebAppDIRAC#274]
When the output sandbox of a job is too big it's uploaded to a standard SE as an LFN. 

From the Job WebApp the "Sanbox -> get Output file(s)" button says:
```
Error: No Output sandbox registered for job 123123123
```

While, from the CLI `dirac-wms-job-get-output` the LFN is correctly resolved (and downloaded).

There is probably the wrong call done...?

**Comment by zmathe** [comment]
No, the same call is used, but the command line is using one more call. When the output sandbox is an LFN, then it downloads it using getFile. I can not do it using the web browser... 
In the sandbox store client we can specify the user certificate:
```python
client = SandboxStoreClient( useCertificates = True,
                                                  delegatedDN = str( userData["user"]["DN"] ),
                                                  delegatedGroup = str( userData["user"]["group"] ),
                                                   setup = userData["setup"] )
```

It is not possible to provide the real user certificate to the DataManager. I can not do nothing only hack what is not good (give properties to the web server host).

**Comment by fstagni** [comment]
Ah I see. No problem, let's close this.
