### ISSUE TITLE
Huge lines in the WebApp log with CS information

### ISSUE THREAD

**Issue by iueda** [DIRACGrid/WebAppDIRAC#317]
Hello,

Why this line is "INFO"?
https://github.com/DIRACGrid/WebAppDIRAC/blob/90043ab9836f173c28f68dfa10243836c2562571/WebApp/handler/ConfigurationManagerHandler.py#L72

I don't think we want see such lines in the log as INFO, which are "huge" and probably not really meaningful.

**Comment by fstagni** [comment]
In https://github.com/DIRACGrid/WebAppDIRAC/pull/318
