### ISSUE TITLE
Search feature does not work

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/WebAppDIRAC#324]
We noticed that the `ctrl+f` search does not work anymore for the CS and the system administrator (and I suspect the other apps too then).
This is a very desired features :)

**Comment by andresailer** [comment]
It works for the text that is visible on the screen, but not for anything outside of what is visible

**Comment by zmathe** [comment]
It is fine in other applications for example JobMonitor

**Comment by zmathe** [comment]
It is introduced in Extjs 6: https://stackoverflow.com/questions/52513580/sencha-extjs6-0-ext-window-window-diagnostic-window-not-able-to-search-text-l

**Comment by fstagni** [comment]
Should be fixed.
