### ISSUE TITLE
Hovering on top of a line in the TS gives the wrong info

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/WebAppDIRAC#339]
See screenshot . The information displayed in the hovering menu has nothing to do with the line on top of which the mouse sits 
![bugHovering](https://user-images.githubusercontent.com/3728211/62948607-f90bbd00-bde4-11e9-82b4-0851a8519cb9.png)

`Replicate-to-IN2P3-Buffer` exists, but it's higher. 
This rings a bell, I think we already had a problem with the offset like this in the past

**Comment by fstagni** [comment]
Looks like fixed to me.
