### ISSUE TITLE
Make web.cfg optional, move its content to dirac.cfg

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/WebAppDIRAC#368]
Currently, `web.cfg` is always lookedup and needed, otherwise weird stuff happens.  Basically what needs to be done is to use the standard way of dirac:  any `.cfg` on the command line should be treated as a configuration file, otherwise, it looks for the default. 
This allows to put all the Web configuration in the standard `etc/dirac.cfg` and also people wanting to stick with a separate `web.cfg` can just add it in the `run` file of the WebApp

**Comment by fstagni** [comment]
Was this done at the end?

**Comment by chaen** [comment]
nop. I talked about it with Zoltan the other day. I'll edit the text to add more information though.

**Comment by fstagni** [comment]
Fixed. Can be closed.
