### ISSUE TITLE
TransformationClient.getTransformationInputDataQuery no longer exists in DIRAC v7r0

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/WebAppDIRAC#377]
https://github.com/DIRACGrid/WebAppDIRAC/blob/c4a9bae8c1c6d995ed9b22845901ff1230d0a7b9/WebApp/handler/TransformationMonitorHandler.py#L276

As long as webapp v4r0 is used both for v6r22 and v7r0 one cannot simply change the function.

PS: I hotfixed on lbcertifdirac70

**Comment by fstagni** [comment]
How did you hotfix?

**Comment by fstagni** [comment]
I see it should be "replaced" by `transClient.getTransformationMetaQuery(prodid, 'Input')` but this means that the hack would be simply go for a `try..except`. Is this the best solution?

**Comment by andresailer** [comment]
Sorry, the bug report was a bit short.

Probably the try/except like check is the best solution.
Looking for  "Unknown method getTransformationInputDataQuery" in the res['Message'] and then trying `getTransformationMetaQuery`? Or rather first getTransformationMetaQuery and the fallback to the old function.

**Comment by fstagni** [comment]
I think the second option: try the new one, fallback to the old. I can take care later, unless you want to do it.

**Comment by fstagni** [comment]
Fixed.
