### ISSUE TITLE
Cannot select/copy information message in System Administrator

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/WebAppDIRAC#383]
After restarting the services on a machine, you get an `information` popup, with all the errors. I can't select this text  in order to copy it.
![Screenshot from 2020-05-26 10-31-48](https://user-images.githubusercontent.com/3728211/82878760-3d171b00-9f3c-11ea-98ce-c639b9a63320.png)

**Comment by fstagni** [comment]
Should be fixed.
