### ISSUE TITLE
DiskOccupancy, index mismatch

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/WebAppDIRAC#391]
The SystemAdministrator Webapp doesn't display anything in the Disk column at the moment. (It didn't for me at least)

I think this comes down to the 'DataIndex' mismatch between WebApp and DIRAC.

https://github.com/DIRACGrid/WebAppDIRAC/blob/7ce791dcc77d28cf83a56239b64b6979c6d5e4b9/WebApp/static/DIRAC/SystemAdministration/classes/SystemAdministration.js#L334-L337

The `DataIndex` from the `InstalledComponentsDB` is 'DiskOccupancy' (I think)

https://github.com/DIRACGrid/DIRAC/blob/9a324b9406094b989fb64f90e2011ea301ea8f7d/FrameworkSystem/DB/InstalledComponentsDB.py#L254
```python
  DiskOccupancy = Column('DiskOccupancy', String(512))
```
https://github.com/DIRACGrid/DIRAC/blob/9a324b9406094b989fb64f90e2011ea301ea8f7d/FrameworkSystem/Service/SystemAdministratorHandler.py#L540
```python
    result['DiskOccupancy'] = summary[1:]
```

I didn't manage to modify the webapp to display the DiskOccupancy, so I might be missing something, instead I added the 'Disk' entry to the returned dictionary and that made the disk occupancy show up, but I think it is more sensible to fix the WebApp code, if someone can confirm that it only takes to modify the 'DataIndex' Entry linked above.

**Comment by fstagni** [comment]
I believe you are right. Which version are you using? Would you be OK to create the PR by yourself?

**Comment by andresailer** [comment]
WebApp v4r0p22. If it is just that line, I can make a PR.

**Comment by andresailer** [comment]
Fixed
