### ISSUE TITLE
BUG: pilot.cfg always added as an argument with JobLaunchpad 

### ISSUE THREAD

**Issue by IgorPelevanyuk** [DIRACGrid/WebAppDIRAC#394]
When launching jobs via JobLaunchpad the "pilot.cfg" string are always added to the arguments. That leads to errors similar to: 
```
/bin/sleep: invalid time interval ‘pilot.cfg’
Try '/bin/sleep --help' for more information.
```
This does not happen if jobs sent using DIRAC API.

**Comment by fstagni** [comment]
As of nowadays, `pilot.cfg` should be removed.

**Comment by TaykYoku** [comment]
I do not see references to pilot.cfg in the code of this project and I have not been able to reproduce such behavior. If this exception is still repeated, more information is needed to understand.

**Comment by fstagni** [comment]
Is it still valid? @IgorPelevanyuk please answer, or we close this ticket.

**Comment by TaykYoku** [comment]
I think it can be closed, because there is no new information about it.
