### ISSUE TITLE
Problem refreshing accounting/monitoring plot when Manual Selection of time span is used

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/WebAppDIRAC#414]
If you create an Accounting (or Monitoring) plot with a "Manual Selection" time, get the plot and then click on the "Refresh" button, it doesn't work: you get a spinning wheel. Same thing if you "Apply" or "Apply all" unless you change the time selection (e.g. go back to "Day", click Apply, then back to "Manual Selection"  and Apply again)

**Comment by TaykYoku** [comment]
Fixed by #415
