### ISSUE TITLE
Organise tabs within desktops (remove Desktop)

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/WebAppDIRAC#427]
Currently it is quite cumbersome to (re)organise tabs within a desktop... 
Drag-and-drop of tabs sometimes gives the impression it works but doesn't and very often screws up the whole set of tabs
Changing the order to applications within the desktop menu is ineffective (or destructive)

Changing the order to tabs should be intuitive and any allowed operation (see above) should work as expected by the user.

**Comment by atsareg** [comment]
Getting back to this issue. I think we should consider simlifying the WebApp framework and leave only tabs view and drop the desktop view. It looked great in the beginning and many appreciated that. But now this is no more fashionable so we can drop it altogether. I think this would be also a good reduction of maintenance/development effort.

**Comment by phicharp** [comment]
I agree with this... Nevertheless it should be more intuitive and practical to change the order of tabs!

A bug/feature that had occurred long ago and that I thought fixed strikes me again: when I reload one of my saved desktops, one of the applications (i.e. tabs) is duplicated, namely the last one appears also before the first one. I delete it, save the desktop again but next time the situation is the same again... According to Zoltan this was some overwriting somewhere when loading the desktop IIRC...

**Comment by hmiyake** [comment]
Currently default view is desktop at Belle II, since one of our application doesn't work with Tab view...
We hope the desktop view is kept at least until the issue is resolved and users are trained to use Tab view.

**Comment by TaykYoku** [comment]
@hmiyake, can you share details about the described application(by email if you want)?

**Comment by michmx** [comment]
Hi @TaykYoku. I am one of the developers maintaining the WebApp described by @hmiyake . In the frontend of the WebApp we define 
```
var oDimensions = GLOBAL.APP.MAIN_VIEW.getViewMainDimensions();
me.launcher.width = oDimensions[0];
```
as done for example in the Job monitor, [line 235](https://github.com/DIRACGrid/WebAppDIRAC/blob/integration/WebApp/static/DIRAC/JobMonitor/classes/JobMonitor.js#L235). Then, `me.launcher.width` is used to define the size of many objects.

I am realizing that in Desktop view `oDimensions[0]` actually contains the width of the window, while in the Tabs view it always is 0. That is the main reason why the WebApp is not compatible with Tabs view. 

Have you identified this before? If you could suggest another way to obtain the view width, we can apply the changes and make the WebApp compatible with Tabs view.

**Comment by TaykYoku** [comment]
Hi @michmx, so you correctly noted. The interface of the "tabs" theme has a slightly different architecture, the interface is divided into two main containers: [left](https://github.com/DIRACGrid/WebAppDIRAC/blob/integration/WebApp/static/core/js/views/tabs/LeftContainer.js) and [right](https://github.com/DIRACGrid/WebAppDIRAC/blob/integration/WebApp/static/core/js/views/tabs/RightContainer.js). Left container for control menus, settings and more and right contains all the widgets which are used to visualise the applications. Each tab in the left container corresponds a widget in the right container.

That is, to get the width of the tab space, you need to ask for it in the right container, e.g.:

`
me.launcher.width = GLOBAL.APP.MAIN_VIEW.getRightContainer().getWidth()
`

**Comment by TaykYoku** [comment]
@michmx @hmiyake , sorry are there any updates on this?

**Comment by TaykYoku** [comment]
@atsareg @fstagni @hmiyake 
Given that so far we know only one application that does not work on the **Tables** theme, then can we agree that starting with 4.3.0 `WebAppDIRAC` and 7.3.0 `DIRAC`, respectively, **Desktop** theme will no longer be?
I think that when it's time to update this installation to `4.3.0`, the application will most likely be updated, if not then I think with my intervention it can be done fairly quickly.

**Comment by atsareg** [comment]
This looks fine to me. Especially because migration of installation to v7r3 is not imminent on the short time scale

**Comment by michmx** [comment]
Hi @TaykYoku. Sorry for the very late answer and the delay on this. I am doing a quick test and we can easily fix the tool using the info from GLOBAL as you shown above (`GLOBAL.APP.MAIN_VIEW.getRightContainer().getWidth()` and `GLOBAL.APP.MAIN_VIEW.getRightContainer().getHeight()`). 

So, please go ahead with the deprecation of the Desktop theme.

**Comment by TaykYoku** [comment]
If you have issue about developing applications on the theme "tabs", please create a new one
