### ISSUE TITLE
Site Summary plots are not correct for transfers

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/WebAppDIRAC#428]
In the Site Summary application, when selecting a site, 6 plots are produced: 4 on jobs and 2 on transfers...  It seems plots for jobs do concern the selected site while transfer plots are for all channels... They should only refer to the SEs at the selected site...

**Comment by phicharp** [comment]
In addition, the status of CEs and SEs only have 2 columns: Name and Type... and the interesting information is missing, i.e. AccessType and Status (Active/banned)

**Comment by fstagni** [comment]
@phicharp is it still the case? This version should be in production in LHCb.

**Comment by phicharp** [comment]
Yes, nothing has changed: DMS plots are still for all channels and SE/CE summary have 2 columns only

**Comment by phicharp** [comment]
![Uploading 210323-SiteSummary.png…]()

**Comment by TaykYoku** [comment]
>In addition, the status of CEs and SEs only have 2 columns: Name and Type... and the interesting information is missing, i.e. AccessType and Status (Active/banned)

The "overview" option on the item provide additional information about element. The nuance is that when the "Overview" right panel opens, there is not much space left in a tables, I'm working on it. 

> In the Site Summary application, when selecting a site, 6 plots are produced: 4 on jobs and 2 on transfers... It seems plots for jobs do concern the selected site while transfer plots are for all channels... They should only refer to the SEs at the selected site...

This should be fixed with #444.

**Comment by TaykYoku** [comment]
I think it can be closed and reopen if additional questions arise
