### ISSUE TITLE
Update doesn't work in accounting plots if manual time range is selected

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/WebAppDIRAC#432]
Almost all in the title: if you create accounting plots with a manual time selection, the "refresh" (aka update) button doesn't work: the spinning wheel turns for a few minutes and the plot is not updated. All works fine if "Last day" or "Last week" is selected...

**Comment by TaykYoku** [comment]
Maybe you meant the "Apply" button, it updates the selected plot. 
Which patch v4r0 you are using? and which version of DIRAC?
