### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/WebAppDIRAC#433]
I think the LHCbWebDIRAC CI configuration can be used as a guide for how to get the linter set up: https://gitlab.cern.ch/lhcb-dirac/LHCbWebDIRAC/-/jobs/11692086

**Comment by fstagni** [comment]
I see that the CI is passing now. Was the configuration fixed?

**Comment by TaykYoku** [comment]
I fixed the configuration, but I think it's worth reviewing it, if I need to add something ..

**Comment by chrisburr** [comment]
This needs changing to be WebAppDIRAC so the test doesn't get skipped:

https://github.com/DIRACGrid/WebAppDIRAC/blob/be4ced9e94e0f84427ea3c724565966cadf52098/.github/workflows/codestyle.yml#L26 

I'll take a closer look soon.

**Comment by TaykYoku** [comment]
I think this should be fixed with #566.
