### ISSUE TITLE
[v4r0] Presenter: "apply" button not working

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/WebAppDIRAC#452]
For a little while, the "apply" button of the presenter does not work properly. The small image is updated, but when you click on it to get the big picture, it is still the old one. I suspect strongly that it comes from that  https://github.com/DIRACGrid/WebAppDIRAC/pull/437/files

Can this be urgently fixed please ? 

How to reproduce (Firefox):

Create a plot, for example
![image](https://user-images.githubusercontent.com/3728211/112450676-ec876e80-8d54-11eb-93c7-926767fe42b9.png)

Now, change the selector (here `Final Transfer Status`), and click `Apply`

![image](https://user-images.githubusercontent.com/3728211/112450861-1fc9fd80-8d55-11eb-8051-8962c9959eac.png)

All nice, but if you click on the image to have it big, you get the old one

![image](https://user-images.githubusercontent.com/3728211/112450960-3a03db80-8d55-11eb-9d18-156bf426a77e.png)

**Comment by fstagni** [comment]
In theory, it should be fixed.
