### ISSUE TITLE
Component Monitoring still not loading

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/WebAppDIRAC#468]
Even after this fix https://github.com/DIRACGrid/WebAppDIRAC/pull/436  the selector for `Component Monitoring` stays waiting forever. We are using v4r2p2

**Comment by TaykYoku** [comment]
Sorry for delay, I tested the `v4r2p2` WebAppDIRAC version with `v7r2p7` DIRAC version and the selector appears after a delay.
Please let me know the DIRAC version of your installation and it would be interesting to read the logs of the monitoring service, if it is not difficult for you.

**Comment by fstagni** [comment]
Won't fix ;-)
