### ISSUE TITLE
Distributing the WebApp for Python 3 installations

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/WebAppDIRAC#485]
Fundamentally three are two things which are specific to distributing the WebApp (and extensions thereof) that need to be handled:

* There are javascript sources that need to be compiled
* Some ExtJS resources need to be installed (images/fonts/themes/more JS)
* nginx needs to be able to find and serve the static

For Python 2 installations this is currently handled by:

1. The WebApp compiler command is called as part of the release process which causes everything to be included in the tarball that is uploaded
2. Extensions do exactly the same thing
3. nginx can find the files at `/opt/dirac/pro/WebAppDIRAC/WebApp/static/`

For the `pip install`ed Python 3 based installations these can be handled as:

### Part 1: Compilation

The setuptools build process is able to run arbitrary code. The simplest approach here would be run the compiler in the docker container by modifying the `setup.py` to be something like:

```python
from setuptools import Command, setup
# Note: distutils must be imported after setuptools
from distutils import log
from setuptools.command.develop import develop as _develop
from wheel.bdist_wheel import bdist_wheel as _bdist_wheel


class build_extjs_sources(Command):
    user_options = []

    def initialize_options(self):
        pass

    def finalize_options(self):
        pass

    def get_inputs(self):
        return []

    def get_outputs(self):
        return []

    def run(self):
        path = os.path.abspath(os.getcwd())
        cmd = [
            "docker",
            "run",
            "--rm",
            f"-v={path}:/shared",
            "-w=/shared",
            "diracgrid/dirac-distribution",
            "/dirac-webapp-compile.py",
            "-D=/shared/src",
            "-n=WebAppDIRAC",
        ]
        log.info('> %r', cmd)
        subprocess.check_call(cmd)


class develop(_develop):
    def run(self):
        self.run_command("build_extjs_sources")
        super().run()


class bdist_wheel(_bdist_wheel):
    def run(self):
        self.run_command("build_extjs_sources")
        super().run()


cmdclass = {
    "develop": develop,
    "bdist_wheel": bdist_wheel,
    "build_extjs_sources": build_extjs_sources,
}

setup(cmdclass=cmdclass)
```

For releases this will run in GitHub actions as part of making the "wheel" to upload to PyPI. And anyone will then be able to install the release without having docker installed.

For the installation of development versions, e.g. `pip install git+https://.../WebAppDIRAC.git@integration` the `setup.py` will be executed causing `docker` to be ran. Alternatively singularity would be slightly lighter or the WebApp compiler script could be integrated with the above `build_extjs_sources.run` function (see part 2).

One thing to consider is that the wheels produced for WebApp DIRAC are relatively large (~41MB) and PyPI has a 2GB cap (that can be increased, [details here](https://github.com/pypa/pypi-support#guidelines-for-upload-limit-requests)). The main cause is the `static/extjs/` directory which is just copied from the ExtJS SDK and isn't changed between versions. I wonder if the best solution would be to make a `DIRACWebAppResources` package which can be uploaded only when the ExtJS SDK is changed. This then makes WebAppDIRAC ~5MB. Thoughts?

### Part 2: Extensions

WebApp extensions will also need to include the above code in their `setup.py` which is probably burdensome. Instead there could be another new package, similar to how [Jupyter handles this](https://github.com/jupyter/jupyter-packaging). This would simplify extension's `setup.py` to be something like:

```python
from setuptools import setup
from diracweb_packaging import extjs_builder_cmdclass

setup(cmdclass=extjs_builder_cmdclass)
```

As well as adding this to their `pyproject.toml`:

```ini
[build-system]
requires = ["diracweb-packaging~=1.0"]
```

This might also lend itself towards moving the `WebAppCompiler` to this new package and removing the dependency on `docker`. At the same time it can be made to do incremental recompiles to make it less painful to develop the WebApp, i.e. `pip install -e .` would recompile what is changed and nothing else and it would just-work. You could also do `python setup.py build_extjs_sources` to achieve the same thing. To improve the portability of this it could have three ways of running the sencha commands, from `$PATH`, using `singularity`, using `docker`.

### Part 3: nginx

Currently the nginx configuration relies on the static directories being fixed due to the `pro` link whereas for Python 3 installations this won't exist in the same way (see https://github.com/DIRACGrid/DIRAC/pull/5215). Instead the static resources will be in `versions/vX.Y.Z-XXXXXXXXXX-x86_64/lib/pythonX.Y/site-packages/WebAppDIRAC/WebApp/static/` and this path will change for every release.

I'm not sure how to handle this. Perhaps the best thing that can be done is to add a new folder, `/opt/dirac/webRoot/resources` which will contain symlinks like:

```
WebAppDIRAC -> /opt/dirac/versions/vX.Y.Z-XXXXXXXXXX-x86_64/lib/pythonX.Y/site-packages/WebAppDIRAC/WebApp/static
LHCbWebDIRAC -> /opt/dirac/versions/vX.Y.Z-XXXXXXXXXX-x86_64/lib/pythonX.Y/site-packages/LHCbWebDIRAC/WebApp/static
```

When WebAppDIRAC is launched in a server installation and `DevelopMode` is off, it will make sure these symlinks correspond to the current installation.

## Summary of proposed actions

* Create a `DIRACWebAppResources` package
* Create a `diracweb_packaging` package
* Make `WebAppDIRAC` update the symlinks in `/opt/dirac/webRoot/resources` each time it's launched

**Comment by fstagni** [comment]
> For releases this will run in GitHub actions as part of making the "wheel" to upload to PyPI. And anyone will then be able to install the release without having docker installed.

You mean, just `pip install WebAppDIRAC`, right?

> For the installation of development versions, e.g. pip install git+https://.../WebAppDIRAC.git@integration the setup.py will be executed causing docker to be ran. Alternatively singularity would be slightly lighter or the WebApp compiler script could be integrated with the above build_extjs_sources.run function (see part 2).

Let's stick with docker

> One thing to consider is that the wheels produced for WebApp DIRAC are relatively large (~41MB) and PyPI has a 2GB cap (that can be increased, details here). The main cause is the static/extjs/ directory which is just copied from the ExtJS SDK and isn't changed between versions. I wonder if the best solution would be to make a DIRACWebAppResources package which can be uploaded only when the ExtJS SDK is changed. This then makes WebAppDIRAC ~5MB. Thoughts?

DIRACWebAppResources package == another pip-installable package?

Apart ExtJS, what would that include?

> WebApp extensions will also need to include the above code in their setup.py which is probably burdensome.

No, it is not burdensome. There are so few WebApp extensions that I would not spend time on new solutions here.

For NGINX: the `pro` link in python3 isn't a link but just a file with a content. In fact, it's a sort of configuration file. It can be used for more "links".

**Comment by chrisburr** [comment]
> You mean, just `pip install WebAppDIRAC`, right?

Yes. I make the distinction as it would also be possible to upload an `sdist` without a `wheel` which would require `docker` during the installation while it compiles the JS sources.

> `DIRACWebAppResources` package == another pip-installable package?
> Apart ExtJS, what would that include?

Yes it would be another package on PyPI and only exists to avoid ~45MB of duplicated data in every release. This would also get cached between updates so it will also make updating slightly faster.

Technically on PyPI it would be a:

* a nearly empty `DIRACWebAppResources/__init__.py`
* a folder of ExtJS resources

The repo in the DIRACGrid organisation would be:

* a README with instructions about how to update it to a new ExtJS version (no need to have CI or anything automatic) 
* a `setup.cfg`
* a `pyproject.toml`
* the `DIRACWebAppResources/__init__.py` file

> No, it is not burdensome. There are so few WebApp extensions that I would not spend time on new solutions here.

It's less than an hour of work to get it set up and centralises the recipe for how to compile a DIRAC WebApp. I'm not thinking of it having CI or anything more than the bare minimum.

> For NGINX: the `pro` link in python3 isn't a link but just a file with a content. In fact, it's a sort of configuration file. It can be used for more "links".

This is true though I don't understand it in the context of my proposal.

**Comment by fstagni** [comment]
> > For NGINX: the `pro` link in python3 isn't a link but just a file with a content. In fact, it's a sort of configuration file. It can be used for more "links".
> 
> This is true though I don't understand it in the context of my proposal.

Mmm right I was seeing things that are not there. Just go with your proposal then.

**Comment by chrisburr** [comment]
(Moving from @TaykYoku's comment at https://github.com/DIRACGrid/DIRAC/pull/5215#issuecomment-867560236 as I think it fits better here)

> Why not create a symlink on site-package in `/opt/dirac` each time you install DIRACOS2?

I thought about it but I don't think DIRAC should be aware of WebApp details like this. I think also it makes confusing situations for cases when people manually intervene on the server to install a new WebApp component or to switch the `old`/`pro` versions but the WebApp resources don't get changed. Making WebAppDIRAC responsible for managing these links ensures that people are always serving the content they expect.

I didn't test it yet but the code I have in mind for doing this is here: https://github.com/DIRACGrid/WebAppDIRAC/pull/484/commits/1c145b781344891bc494fe08d66f0b63f0e52804

**Comment by TaykYoku** [comment]
Sorry, maybe I don't understand well, /opt/dirac/bashrc refers to diracosrc which lies in the version directory, if switch `old`/`pro` then won't it work?

**Comment by chrisburr** [comment]
`/opt/dirac/bashrc` is a file which is generated automatically as part of `install_site.sh` but that is otherwise managed by the person responsible for the machine. This allows the sysadmin to add custom environment configuration in the way everyone is used to doing.

A simple Python 3 only version is generated here: https://github.com/DIRACGrid/management/pull/40/files#diff-2f2f2f97aae4f5b985b613f75746c98e079456bc0d730d2965c831cd4d096135R114-R126

In order to make an installation support Python 2 and Python 3 installs it would be something like this which

1. Finds which installation to use in the `versions/` directory
2. Activates DIRACOS
3. Sets additional environment configuration

```bash
# Find which DIRAC installation to use
if [ -L "/opt/dirac/pro" ]; then
    # Python 2 based installation
    py3_based=0
    default_dirac=/opt/dirac/pro
else
    # Python 3 based installation
    py3_based=1
    default_dirac="/opt/dirac/versions/$(cat "/opt/dirac/pro")-$(uname -m)"
fi
if [ -n "${DIRAC:-}" ] && [[ "${default_dirac}" != "${DIRAC:-}" ]]; then
    echo DIRAC installation path overridden to ${DIRAC}
fi
export DIRAC=${DIRAC:-${default_dirac}}
unset default_dirac

# CAs path for SSL verification
export X509_CERT_DIR=${X509_CERT_DIR:-"/opt/dirac/etc/grid-security/certificates"}
export X509_VOMS_DIR=${X509_VOMS_DIR:-"/opt/dirac/etc/grid-security/vomsdir"}
export X509_VOMSES=${X509_VOMSES:-"/opt/dirac/etc/grid-security/vomses"}

# Source DIRACOS
. $DIRAC/diracosrc

# Configuration which is only required for legacy installations
if [ py3_based = 0]; then
    export PYTHONUNBUFFERED=yes
    export PYTHONOPTIMIZE=x
    export DIRACSCRIPTS=$DIRAC/scripts
    export TERMINFO=$DIRACOS/usr/share/terminfo:/usr/share/terminfo:/etc/terminfo
    export RRD_DEFAULT_FONT=$DIRACOS/usr/share/fonts/DejaVuSansMono-Roman.ttf
    # Prepend the PYTHONPATH, the LD_LIBRARY_PATH, and the DYLD_LIBRARY_PATH
    ( echo $PATH | grep -q $DIRACSCRIPTS ) || export PATH=$DIRACSCRIPTS:$PATH
    ( echo $PYTHONPATH | grep -q $DIRAC ) || export PYTHONPATH=$DIRAC
    # new OpenSSL version require OPENSSL_CONF to point to some accessible location
    export OPENSSL_CONF=/tmp
fi

# The remainder of this file is custom environment configuration for this specific installation

# IPv6 support
export GLOBUS_IO_IPV6=TRUE
export GLOBUS_FTP_CLIENT_IPV6=TRUE

# Fork support for xrootd
export XRD_RUNFORKHANDLER=1

export DIRAC_GFAL_GRIDFTP_SESSION_REUSE=True

```

**Comment by TaykYoku** [comment]
Ok, this is if `/pro` is a file. I propose to consider a slightly different way, if of course I do not miss something important that will make this approach impossible or unacceptable.

> In order to make an installation support Python 2 and Python 3 installs it would be something like this which
> 
> Finds which installation to use in the versions/ directory
> Activates DIRACOS
> Sets additional environment configuration

1. if you leave the `pro` as link then it seems that you will not have to look for which installation to use in the `versions` directory, it will always be the `pro` directory. 

Then support for the legacy installation can be provided as follows, what am I missing?

```
# Source DIRACOS
[[ -f /opt/dirac/pro/diracosrc ]] && . /opt/dirac/pro/diracosrc

# Make an installation support Python 2 and Python 3 installs
if [ "$(python -V)" =~ "Python 3" ]; then
    # Python 3 based installation
else
    # Python 2 based installation
    # Configuration which is only required for legacy installations
    ...
fi

# The remainder of this file is custom environment configuration for this specific installation
...
```

**Comment by chrisburr** [comment]
The reason for changing `pro` from a symlink to a file is explained here: https://github.com/DIRACGrid/DIRAC/pull/5215
