### ISSUE TITLE
hostnames in SystemAdministrator selectors appear as '[object Object]'

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/WebAppDIRAC#519]
All in the title and this image

![systemAdministrator](https://user-images.githubusercontent.com/3728211/128370281-c734956a-890e-4dba-b7ac-522e6c3339ad.png)

**Comment by TaykYoku** [comment]
it would be good to know at least the version of DIRAC/WebApp

**Comment by chaen** [comment]
Oups indeed I thought I added it. DIRAC v7r2p19 WebApp v4r2p6

**Comment by TaykYoku** [comment]
Please, update WebApp to v4r2p8.
