### ISSUE TITLE
ES based Component Monitoring broken in v7r2

### ISSUE THREAD

**Issue by arrabito** [DIRACGrid/WebAppDIRAC#532]
ES based Component Monitoring does not work correctly after update to v7r2p11 (previous working tested version was v7r1p28)?

Some fields that were previously filled are not anymore. Currently we have monitoring data in ES only for:
cycleDuration
cycles
serviceResponseTime

while previously we had: RunningThread, Memory Usage, etc.

Also, plotting for instance the AgentCycleDuration "by host", returns a plot grouped by hosts that seem to be worker nodes instead of DIRAC server hosts.

**Comment by fstagni** [comment]
Won't fix ;-)
