### ISSUE TITLE
Disable rebase/squash merging

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/WebAppDIRAC#592]
@fstagni To prevent confusion, can you disable the "Allow rebase merging" and "Allow squash merging"? The options should be visiable at:

https://github.com/DIRACGrid/WebAppDIRAC/settings#merge-button-settings

_Originally posted by @chrisburr in https://github.com/DIRACGrid/WebAppDIRAC/issues/590#issuecomment-948574071_

**Comment by fstagni** [comment]
Done.
