### ISSUE TITLE
Accounting: insert text instead of using a pull-down menu for the JobGroup selector

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/WebAppDIRAC#609]
(originally posted by @phicharp in ML)

Has anyone ever managed to make an accounting plot about jobs using the JobGroup selector? For me it blocks my portal page for a verrrrryyyyyyy long time and in the end nothing appears in the selector. This is probably due to the (too) large number of JobGroup values (i.e. probably all productions ever) but this is rather annoying:
1. because we may want to make such plots selecting specific productions
2. it blocks completely the application (and consumes 100% of a CPU)
JobGroup selector for job monitoring works fine but probably this is because here we only have the transformations that exist.

I would suggest to suppress the pulldown menu for this selector and allow the user to enter just a transformation number (not sure if this is possible) but as it is, we cannot use it…

**Comment by TaykYoku** [comment]
I will note that the [Ext.form.field.Tag](https://docs.sencha.com/extjs/7.3.1/classic/Ext.form.field.Tag.html) element is involved here, it seems that it does not contain a ready-made solution, just as and for #425.

I'll see if it possible to implement something like regex.

> enter just a transformation number

Did not quite understand what kind of number, @fstagni if not difficult to add a link to it in the documentation or in the code.

**Comment by fstagni** [comment]
> > enter just a transformation number
> 
> Did not quite understand what kind of number, @fstagni if not difficult to add a link to it in the documentation or in the code.

@phicharp is simply suggesting to suppress the pull-down menu, and use instead a free-text field.

**Comment by TaykYoku** [comment]
@fstagni @phicharp I propose to consider the following solution #621
