### ISSUE TITLE
[integration] New WebHandler not able to do request on behalf of a user

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/WebAppDIRAC#653]
Up to now, a client would connect to the WebApp using his certificate. The WebApp would extract the user DN, and then query the DIRAC services (diset or https) using its own server certificate but on behalf of the user. This relied on the `ThreadConfig` object and the `ExtraConfig` arguments of the RPC calls. 

That behavior is now broken.

We have noticed it during an LHCbDIRAC hackaton because this the `JobManager` would not allow any of us the display jobs. This is because in the part of code below, the remote credentials are the one of the Server, without the user extra credentials

https://github.com/DIRACGrid/DIRAC/blob/871cbf92e8365e6376061183c525a57c9196da8d/src/DIRAC/WorkloadManagementSystem/Service/JobMonitoringHandler.py#L325-L337

The mechanism of `extraCredential` itself is not broken though, I could test it by running this script on a host without proxy

```python
from pprint import pprint
from DIRAC.Core.DISET.ThreadConfig import ThreadConfig
from DIRAC.Core.Base.Client import Client
threadConfig = ThreadConfig()
threadConfig.setDN(myUSERDN)
threadConfig.setGroup('lhcb_user')

print("with https")
httpsCred = Client(url='https://lhcbvoboxcertif00.cern.ch:8443/WorkloadManagement/JobManager').whoami()['Value']
pprint(httpsCred)
```

```python
with https
{'DN': 'myUserDN',
 'group': 'lhcb_user',
 'isLimitedProxy': False,
 'isProxy': False,
 'issuer': '/DC=ch/DC=cern/CN=CERN Grid Certification Authority',
 'properties': ['NormalUser', 'PrivateLimitedDelegation'],
 'secondsLeft': 16006027,
 'subject': 'myHostDN'
 'username': 'chaen',
 'validDN': False,
 'validGroup': False}
```

So the problem lies with how the new WebHandler uses that `ThreadConfig` object and the interaction with the `async` methods.

**Comment by TaykYoku** [comment]
https://github.com/DIRACGrid/DIRAC/pull/6142 should fix this. My tests have shown that remote credentials after this fix return user credentials as it should be.

**Comment by fstagni** [comment]
I close this one as it seems to have been solved. It can be re-opened in case it is not true (pending a non-vanilla DIRAC hackathon)
