### ISSUE TITLE
Replace WebHandler with _WebHandler

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/WebAppDIRAC#658]
Apologies if I haven't found where this is was discussed but it seems that we currently have two implementations of the `WebHandler`:

https://github.com/DIRACGrid/WebAppDIRAC/blob/d70c268ff47fc051ca29fd0415fcaeb0e7587f2a/src/WebAppDIRAC/Lib/WebHandler.py#L161

https://github.com/DIRACGrid/WebAppDIRAC/blob/d70c268ff47fc051ca29fd0415fcaeb0e7587f2a/src/WebAppDIRAC/Lib/WebHandler.py#L401

Most classes seem to be using `_WebHandler` which appears to be a much nicer implementation which delegates every request to a dedicated thread so the `@asyncGen` and ` yield self.threadTask` stuff isn't needed like in:

https://github.com/DIRACGrid/WebAppDIRAC/blob/d70c268ff47fc051ca29fd0415fcaeb0e7587f2a/src/WebAppDIRAC/WebApp/handler/SystemAdministrationHandler.py#L91-L92

https://github.com/DIRACGrid/WebAppDIRAC/blob/d70c268ff47fc051ca29fd0415fcaeb0e7587f2a/src/WebAppDIRAC/WebApp/handler/SystemAdministrationHandler.py#L104

Is there a reason why we need both implementations? I think we should just move the legacy style handlers to the new one and delete the old implementation.

**Comment by TaykYoku** [comment]
Yes, you are absolutely right, now the process of switching to `_WebHandler` is underway, as soon as it ends `WebHandler` is simply removed and `_WebHandler` will be renamed to `WebHandler`.

**Comment by chrisburr** [comment]
I think it would be good to deal with this before releasing v5.0 so we have a cleaner starting point fot v5.1 (which I have some ideas for).

Quickly checking these are the modules which need to be updated in vanilla DIRAC. I'll try to start working through them now starting from the top and checking them off:

- [x] `src/WebAppDIRAC/WebApp/handler/ConfigurationManagerHandler.py`
- [x] `src/WebAppDIRAC/WebApp/handler/ProxyManagerHandler.py`
- [x] `src/WebAppDIRAC/WebApp/handler/ProxyUploadHandler.py`
- [x] `src/WebAppDIRAC/WebApp/handler/PublicStateManagerHandler.py`
- [x] `src/WebAppDIRAC/WebApp/handler/RegistryManagerHandler.py`
- [x] `src/WebAppDIRAC/WebApp/handler/RequestMonitorHandler.py`
- [x] `src/WebAppDIRAC/WebApp/handler/ResourceSummaryHandler.py`
- [x] `src/WebAppDIRAC/WebApp/handler/SiteSummaryHandler.py`
- [x] `src/WebAppDIRAC/WebApp/handler/SpaceOccupancyHandler.py`
- [x] `src/WebAppDIRAC/WebApp/handler/SystemAdministrationHandler.py`
- [x] `src/WebAppDIRAC/WebApp/handler/TransformationMonitorHandler.py`
- [x] `src/WebAppDIRAC/WebApp/handler/VMDiracHandler.py`

**Comment by chrisburr** [comment]
Excellent work getting this all done @TaykYoku! 🍰
