### ISSUE TITLE
Document how to migrate to new _WebHandler class in release wiki

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/WebAppDIRAC#672]
> This is not entirely true, there are some nuances. The very idea of creating `_WebHandler` based on `BaseRequestHandler` is to change the style of writing handlers. In addition to removing `@asyncGen` + `yield self.threadTask` and changing `_WebHandler` to `WebHandler`, for ex. you need to use `return` instead of `self.finish`, describe **request arguments** via **function annotations**.

_Originally posted by @TaykYoku in https://github.com/DIRACGrid/WebAppDIRAC/pull/660#issuecomment-1159063746

**Comment by TaykYoku** [comment]
https://github.com/DIRACGrid/DIRAC/wiki/How-to-migrate-to-new-_WebHandler-class
