### ISSUE TITLE
Job Monitor app do not show new jobs info for some time after submission

### ISSUE THREAD

**Issue by IgorPelevanyuk** [DIRACGrid/WebAppDIRAC#697]
Hello, 

I observe strange behavior of Job Monitor. It takes a minute to begin showing newly submitted jobs. From my perspective it looks like some caching mechanism. Because, if I take JobID and write it in the selector field, I will get the infromation about it. But right after that I can try to get all jobs again and new job will be absent.
Of couse, this problem disappear after some time, but not seing new jobs in list is quite annoyung. 
Is it expected behavior?

**Comment by marianne013** [comment]
We see the same for any state change, but have so far filed it under "annoying but harmless".

**Comment by IgorPelevanyuk** [comment]
I see it more like "harmless but annoying" :)
