### ISSUE TITLE
Unable to download csv data when data source is ES

### ISSUE THREAD

**Issue by EwoudK** [DIRACGrid/WebAppDIRAC#722]
Saving csv data from the portal where the data source is ElasticSearch yields an 'empty' csv file (it contains only the header + one row where the only non-null value is the epoch).

[e1335f4af7f7eb3caf2acc0a3b6feae0.csv](https://github.com/DIRACGrid/WebAppDIRAC/files/10559252/e1335f4af7f7eb3caf2acc0a3b6feae0.csv)

**Comment by fstagni** [comment]
Won't solve.
