### ISSUE TITLE
Allow setting default WebApp theme?

### ISSUE THREAD

**Issue by sfayer** [DIRACGrid/WebAppDIRAC#738]
Hi,

It appears the theme setting in the webapp was marked as obsolete and it's now statically set:

https://github.com/DIRACGrid/WebAppDIRAC/blob/54ffd343716903b8db91da00e0c17b4fff736ce0/src/WebAppDIRAC/Lib/Conf.py#L241-L242
https://github.com/DIRACGrid/WebAppDIRAC/blob/54ffd343716903b8db91da00e0c17b4fff736ce0/src/WebAppDIRAC/WebApp/handler/RootHandler.py#L155

(It's a bit of a muddle, the getTheme used to return a *view* and optionally a theme separated by a `:`).

We were using this functionality to give our users a different default theme. Would there be any objections to re-instating this bit of code? Specifically I'd like to make getTheme return a theme name from the CS (or `crisp` as the default) and use that in web_index.

Regards,
Simon

**Comment by fstagni** [comment]
This was discussed long time ago, in order to simplify things. If that's a requirement for you, go ahead with your plan.
